// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  tutorialSidebar: [
    'overview',
    {
      type: 'category',
      label: 'Package Structure',
      collapsed: true,
      items: [{type: 'autogenerated', dirName: 'package_structure'}],
    },
{
      type: 'category',
      label: 'Script Types',
      collapsed: true,
      items: [{type: 'autogenerated', dirName: 'script_types'}],
    },
    {
      type: 'category',
      label: 'Host Namespace',
      collapsed: true,
      items: [{type: 'autogenerated', dirName: 'host'}],
    },
    {
      type: 'category',
      label: 'SDK Files',
      collapsed: true,
      items: [{type: 'autogenerated', dirName: 'sdk'}],
    },
    {
      type: 'category',
      label: 'Context Object',
      collapsed: true,
      items: [{type: 'autogenerated', dirName: 'context'}],
    },
    {
      type: 'category',
      label: 'Objects',
      collapsed: true,
      items: [{type: 'autogenerated', dirName: 'objects'}],
    },
    {
      type: 'category',
      label: 'Skin',
      collapsed: true,
      items: [{type: 'autogenerated', dirName: 'skin'}],
    },
    {
      type: 'category',
      label: 'Utilities',
      collapsed: true,
      items: [{type: 'autogenerated', dirName: 'utilities'}],
    },
    'api_index',
  ],

  scriptsSidebar: [
    {type: 'autogenerated', dirName: 'scripts'},
  ],
};

export default sidebars;
